### ISSUE TITLE
Wrong Content-Type for HTML5 documents - text/sgml 

### ISSUE THREAD

**Issue by vgamula** [kachayev/nasus#1]
In HTML5 documents doctype does not refer to any DTDs, usually specified [like this](https://dev.w3.org/html5/html-author/#doctype-declaration):
```
<!DOCTYPE html>
```

Seems like [the tibrary](https://github.com/arimus/jmimemagic), that is used for detecting MIME types, does not deal properly with such definitions, they are parsed as `text/sgml` https://github.com/arimus/jmimemagic/issues/27.

Example:

```
> cat test.html
<!DOCTYPE html>
<html>
<head>
    <title>test</title>
</head>
<body>
test
</body>
</html>


> clj -Sdeps '{:deps {net.sf.jmimemagic/jmimemagic {:mvn/version "0.1.5"}}}' -r
Clojure 1.9.0
user=> (require '[clojure.java.io :as io])
nil
user=> (import '(net.sf.jmimemagic Magic))
net.sf.jmimemagic.Magic
user=> (def f (io/file (str (System/getProperty "user.dir") "/test.html")))
#'user/f
user=> (.getMimeType (Magic/getMagicMatch f true))
log4j:WARN No appenders could be found for logger (net.sf.jmimemagic.Magic).
log4j:WARN Please initialize the log4j system properly.
"text/sgml"
```

So, it is not an issue with Nasus itself. Server just [sends](https://github.com/kachayev/nasus/blob/master/src/http/server.clj#L85) wrong `Content-Type` and browsers cannot render it properly, as they expect HTML pages to be with `Content-Type: text/html`.

**Comment by kachayev** [comment]
Okay, so there 2 approaches here:

* find a way to explain to `jMimeMagic` the correct mime type
* replace mime type detection library 

I'm okay with any of those. Do you want to provide a fix?

**Comment by vgamula** [comment]
@kachayev, sure, I'm going to replace it with [`org.apache.tika`](https://tika.apache.org/) (`tika-core` only) as it seems to be the best tool for detecting MIME types. There is a [wrapper](https://github.com/michaelklishin/pantomime) on Clojure but I don't think we really need it.

**Comment by kachayev** [comment]
Thanks! I also had to update log deps, looks like `log4j` was used transitively before. Will do a new release shortly.
