### ISSUE TITLE
Internal server error when getting empty file

### ISSUE THREAD

**Issue by emlyn** [kachayev/nasus#3]
Trying to get an empty file returns a 500 response with a `MagicMatchNotFoundException` exception and stacktrace.  I imagine this could also happen for other files where the mime type cannot be determined.

It should probably fall back to a default like `application/octet-stream` if the mime type cannot be determined.

**Comment by emlyn** [comment]
Actually, according to [this](https://stackoverflow.com/questions/1176022/unknown-file-type-mime/28652339#28652339), the Content-Type header should be omitted if the mime type is not known.

**Comment by kachayev** [comment]
Github now automatically closes the issue instead of mentioning it based on commit messages? 🤔

**Comment by kachayev** [comment]
Released `0.1.2`. Thanks!
